name: gasindex
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - numpy
  - ipykernel
  - openpyxl
  - requests
  - lxml
  - beautifulsoup4
  - scikit-learn
  - jax